### ISSUE TITLE
Stops working if wifi disconnects and reconnects

### ISSUE THREAD

**Issue by devnoname120** [devnoname120/vitacompanion#1]
Looks like the net_ctl callback needs to be improved.

Note: As a workaround I restart my vita when it happens, [this button](https://github.com/devnoname120/vita-restart) makes it convenient.

**Comment by gnuton** [comment]
what about listening for ScePowerCallback to get tear down the server when going to sleep and setting the connection up again when the device wakes up?

**Comment by devnoname120** [comment]
@gnuton If you fix it, please do a pull request! 👍
